baseURL = "https://juniordevmyanmar.github.io/"
languageCode = "en-us"
title = "Home - JuniorDev Myanmar"
theme = "minimal"
publishDir = "docs"

[params]
    accent = "blue"
    author = "JuniorDev.mm"
    description = "Official website for JuniorDev Myanmar"
    showBorder = true
    backgroundColor = "white"
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift","javascript"]
    font = "Raleway"
    profilePic = "images/logox200x200.png"
    copyright = "မြန်မာပြည် မှ JuniorDev များမှ ဂုဏ်ယူစွာဖြင့်တည်ဆောက်သည်။"
    

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
    url = "https://github.com/juniordevmyanmar/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/groups/543922492942919/"
    name = "facebook"
    weight = 2